name: CI-scaffold-next

on:
  push:
    branches:
      - dev
      - main
    # Only consider those paths to trigger the action
    paths:
      - 'packages/**'
      - 'package.json'
      - '*.lock'
      - '.yarnrc.yml'
      - 'tsconfig.base.json'
      - '.prettier*'
      - '.github/**'

  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    # Only consider those paths to trigger the action
    paths:
      - 'packages/**'
      - 'package.json'
      - '*.lock'
      - '.yarnrc.yml'
      - 'tsconfig.base.json'
      - '.prettier*'
      - '.github/**'
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: 📥 Monorepo install
        uses: ./.github/actions/yarn-nm-install

      # see https://github.com/vercel/next.js/pull/27362
      - name: Restore nextjs build scaffold-next-app from cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/packages/scaffold-next/.next/cache
            ${{ github.workspace }}/.cache
            ${{ github.workspace }}/**/tsconfig.tsbuildinfo

          key: ${{ runner.os }}-scaffold-next-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('packages/scaffold-next/src/**.[jt]sx?', 'packages/scaffold-next/src/**.json') }}
          restore-keys: |
            ${{ runner.os }}-scaffold-next-${{ hashFiles('**/yarn.lock') }}-

      - name: Typecheck
        working-directory: packages/scaffold-next
        run: |
          yarn typecheck

      - name: Linter
        working-directory: packages/scaffold-next
        run: |
          yarn lint

      - name: Unit tests
        working-directory: packages/scaffold-next
        run: |
          yarn test-unit

      - name: Build web-app
        working-directory: packages/scaffold-next
        run: |
          yarn build
        env:
          # Speed up build: they are linted in a previous step
          NEXTJS_IGNORE_ESLINT: true
          # Speed up build: they are typechecked in a previous step
          NEXTJS_IGNORE_TYPECHECK: true
          # Speed up build: don't run if not needed, enable if it becomes needed
          NEXT_DISABLE_SOURCEMAPS: true
          # Don't send telemetry for ci
          NEXT_TELEMETRY_DISABLED: true
          # To allow checking size-limits
          NEXTJS_DISABLE_SENTRY: false
          # Fully disable sentry upload
          NEXTJS_SENTRY_UPLOAD_DRY_RUN: true

      - name: Check browser bundle size limits
        working-directory: packages/scaffold-next
        run: |
          yarn check-size

      # - name: Check ecmascript checks for build files
      #   working-directory: packages/scaffold-next
      #   run: |
      #     yarn check-dist
